-- MySQL Script generated by MySQL Workbench
-- Sat May  4 15:19:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `uid` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `rib` VARCHAR(255) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`association` (
  `idassociation` INT NOT NULL AUTO_INCREMENT,
  `associationname` VARCHAR(45) NULL,
  `budget` DECIMAL(45) NULL,
  `rib` VARCHAR(255) NULL,
  PRIMARY KEY (`idassociation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`associationmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`associationmember` (
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `association_idassociation`),
  INDEX `fk_associationmember_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_associationmember_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_associationmember_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idadmin`, `user_iduser`),
  INDEX `fk_admin_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `transactionname` VARCHAR(45) NULL,
  `valeur` DECIMAL(10,2) NULL,
  `date` DATETIME NULL,
  `outorin` BINARY(1) NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`idtransaction`, `association_idassociation`),
  INDEX `fk_transaction_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demanderemboursement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demanderemboursement` (
  `iddemanderemboursement` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `montant` DECIMAL(10,2) NULL,
  `imagepath` VARCHAR(255) NULL,
  `statut` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`iddemanderemboursement`, `user_iduser`, `association_idassociation`),
  INDEX `fk_demanderemboursement_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_demanderemboursement_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_demanderemboursement_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demanderemboursement_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`presidents` (
  `idpresidents` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`idpresidents`, `user_iduser`, `association_idassociation`),
  INDEX `fk_presidents_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_presidents_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_presidents_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presidents_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vicepresidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vicepresidents` (
  `idvicepresidents` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`idvicepresidents`, `user_iduser`, `association_idassociation`),
  INDEX `fk_vicepresidents_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_vicepresidents_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_vicepresidents_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vicepresidents_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tresoriers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tresoriers` (
  `idtresoriers` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`idtresoriers`, `user_iduser`, `association_idassociation`),
  INDEX `fk_tresoriers_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_tresoriers_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_tresoriers_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tresoriers_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secretairegeneral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secretairegeneral` (
  `idsecretairegeneral` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `association_idassociation` INT NOT NULL,
  PRIMARY KEY (`idsecretairegeneral`, `user_iduser`, `association_idassociation`),
  INDEX `fk_secretairegeneral_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_secretairegeneral_association1_idx` (`association_idassociation` ASC) VISIBLE,
  CONSTRAINT `fk_secretairegeneral_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_secretairegeneral_association1`
    FOREIGN KEY (`association_idassociation`)
    REFERENCES `mydb`.`association` (`idassociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
